---
name-template: "v$NEXT_PATCH"
tag-template: "v$NEXT_PATCH"
categories:
  - title: "Bug Fixes"
    labels:
      - "bug"
  - title: "Features"
    labels:
      - "feature"
  - title: "Documentation"
    labels:
      - "documentation"
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&@#'

template: |
  ## Changelog

  $CHANGES
