name: module3_task3

'on':
  push:
    branches:
      - main
    tags:
      - '*'
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Setup environment
        run: |
          cd ./module3_task3
          ./setup.sh

      - name: Build and Package
        run: |
          cd ./module3_task3
          make build
          make package

      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: awesome-website
          path: ./module3_task3/awesome-website.zip

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo-token: ${{ secrets.MY_GITHUB_TOKEN }}
          files: |
            ./module3_task3/awesome-website.zip
            ./module3_task3/DEPLOY.md
