---
name: module3_task1

"on":
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          cd ./module3_task1
          ./setup.sh

      - name: Build
        run: |
          cd ./module3_task1
          make build
