---
name: module4_task0

'on':
  push:
    branches: [main]
    tags:
      - '*'
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      deployments: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          cd ./module4_task0
          ./setup.sh

      - name: Build
        run: |
          cd ./module4_task0
          make build

      - name: Run package
        run: |
          cd ./module4_task0
          make package

      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: awesome-website
          path: ./module4_task0/awesome-website.zip

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './module4_task0/dist'
          enable-pull-request-comment: true
          production-branch: main
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          deploy-message: '🚀 Deployed on'
          publish-message: '🎉 Published on'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

  create-release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      - name: Check-out code
        uses: actions/checkout@v2

      - name: Create Package
        run: |
          cd module4_task0
          make package

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./module4_task0/awesome-website.zip
          body_path: ./module4_task0/DEPLOY.md
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
