---
name: module3_task1

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          go-version: 1.15.15

      - name: Download Go modules
        run: go mod download

      - name: Setup environment
        run: |
          cd ./module3_task1
          ./setup.sh

      - name: Build
        run: |
          cd ./module3_task1
          make build
